# Typus Roles Configuration File
#
# Use the README file as a reference to customize settings.

admin:
  Comment: read, update, delete
  City: create, read, update, delete
  Country: create, read, update, delete
  Event: create, read, update, delete
  User: create, read, update, delete
